# Generated by Django 3.1.4 on 2020-12-13 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=20)),
                ('hire_date', models.IntegerField()),
                ('position', models.CharField(max_length=3)),
                ('second_position', models.CharField(max_length=4)),
                ('salary', models.IntegerField()),
                ('max_bonus', models.IntegerField()),
            ],
        ),
    ]
