# Generated by Django 3.1.4 on 2020-12-14 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_utd', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='pic',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
