# Generated by Django 3.1.4 on 2020-12-14 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mun_utd', '0002_player_pic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='player',
            old_name='pic',
            new_name='picture',
        ),
    ]
