# Generated by Django 3.1.4 on 2020-12-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_utd', '0003_auto_20201214_1512'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='picture',
            field=models.ImageField(upload_to=''),
        ),
    ]
