# Generated by Django 3.1.4 on 2020-12-20 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mun_utd', '0004_auto_20201218_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='slug',
            field=models.SlugField(default='player'),
        ),
    ]
